FROM mysql:latest

# Variables de entorno
ENV MYSQL_ROOT_PASSWORD=123456 \
    MYSQL_DATABASE=picking \
    MYSQL_USER=username \
    MYSQL_PASSWORD=123456

# Copiar script SQL para crear la base de datos
COPY ./create_db.sql /docker-entrypoint-initdb.d/

# Exponer el puerto 3306
EXPOSE 3306
