FROM mysql:latest

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=123456 \
    MYSQL_DATABASE=picking \
    MYSQL_USER=username \
    MYSQL_PASSWORD=123456

# Copy sql script to create database
COPY db.sql /docker-entrypoint-initdb.d/

# Expose port 3306
EXPOSE 3306
