version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: picking
      MYSQL_USER: username
      MYSQL_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: username
      DB_PASSWORD: 123456
      DB_NAME: picking
    depends_on:
      - db
    links:
      - db

volumes:
  db_data:
