name: Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install
      
    - name: Run lint
      run: npm run lint
      
    - name: Run Prettier
      run: npm run prettier
      
    - name: Run tests
      run: npm test
